export const FETCH_PRODUCT_PENDING = "FETCH_PRODUCT_PENDING";
export const FETCH_PRODUCT_FULFILLED = "FETCH_PRODUCT_FULFILLED";
export const FETCH_PRODUCT_REJECTED = "FETCH_PRODUCT_REJECTED";

export const FETCH_MY_PRODUCT_PENDING = "FETCH_MY_PRODUCT_PENDING";
export const FETCH_MY_PRODUCT_FULFILLED = "FETCH_MY_PRODUCT_FULFILLED";
export const FETCH_MY_PRODUCT_REJECTED = "FETCH_MY_PRODUCT_REJECTED";

export const ADD_PRODUCT_PENDING = "ADD_PRODUCT_PENDING";
export const ADD_PRODUCT_FULFILLED = "ADD_PRODUCT_FULFILLED";
export const ADD_PRODUCT_REJECTED = "ADD_PRODUCT_REJECTED";

export const EDIT_PRODUCT_PENDING = "EDIT_PRODUCT_PENDING";
export const EDIT_PRODUCT_FULFILLED = "EDIT_PRODUCT_FULFILLED";
export const EDIT_PRODUCT_REJECTED = "EDIT_PRODUCT_REJECTED";

export const REMOVE_PRODUCT_PENDING = "REMOVE_PRODUCT_PENDING";
export const REMOVE_PRODUCT_FULFILLED = "REMOVE_PRODUCT_FULFILLED";
export const REMOVE_PRODUCT_REJECTED = "REMOVE_PRODUCT";

// export const TOGGLE_GRID = "TOGGLE_GRID";